### ISSUE TITLE
future compatibility problem in dependencies

### ISSUE THREAD

**Issue by hdhoang** [justinnoah/rtracker#16]
Hi, due to rust-lang/rust#49799, one of your dependencies will no longer build. From looking at your
Cargo.toml, we recommend you upgrade to
rusqlite version 0.14 or later (you will also need to bump r2d2_rusqlite's version too I think). Thanks for your attention!

**Comment by justinnoah** [comment]
Thank you for the notice @hdhoang! As of v0.8.0 rtracker compiles with Rust 1.36.0.
